// Code generated by inspc. DO NOT EDIT.
// source: github.com/koykov/dyntpl/testobj

package testobj_ins

import (
	"github.com/koykov/inspector"
)

func init() {
	inspector.RegisterInspector("BenchRow", &BenchRowInspector{})
	inspector.RegisterInspector("BenchRows", &BenchRowsInspector{})
	inspector.RegisterInspector("MarshalData", &MarshalDataInspector{})
	inspector.RegisterInspector("MarshalRow", &MarshalRowInspector{})
}
